/**
 * Semantic layer: one definition per metric (docs/13 §3–4). Dashboards, the Insight Hand, benchmarks
 * and packs all render from these definitions; no surface computes a metric its own way.
 */
export type MetricGroup = 'access' | 'operations' | 'clinical_quality' | 'patient_experience' | 'referrer' | 'revenue_cycle' | 'finance' | 'workforce' | 'assets' | 'compliance' | 'ai_ops' | 'shareholder';
export type Direction = 'higher' | 'lower' | 'band';
export type Freshness = 'live' | 'near_live' | 'daily' | 'monthly';
export type MetricUnit = 'count' | 'pct' | 'minutes' | 'hours' | 'days' | 'cents' | 'ratio' | 'score' | 'months';

export interface MetricDefinition {
  id: string;
  name: string;
  group: MetricGroup;
  description: string;
  /** Numerator / denominator (or aggregate) over named facts, in plain English. */
  formula: string;
  grain: string;
  owner: string;
  /** Illustrative default target; practices override as reference data. */
  target: number | null;
  targetBand?: [number, number];
  targetLabel: string;
  direction: Direction;
  unit: MetricUnit;
  freshness: Freshness;
  /** Source tables the computation reads (owned by other clusters unless core); null values when absent. */
  sources: string[];
  privacyClass: 'T0' | 'T1' | 'T3';
  version: number;
  /** Keywords the Insight Hand matches questions against. */
  keywords: string[];
}

const GROUP_LABEL: Record<MetricGroup, string> = {
  access: 'Access', operations: 'Operations', clinical_quality: 'Clinical quality', patient_experience: 'Patient experience', referrer: 'Referrer',
  revenue_cycle: 'Revenue cycle', finance: 'Finance', workforce: 'Workforce', assets: 'Assets', compliance: 'Compliance and risk', ai_ops: 'AI operations', shareholder: 'Shareholder',
};
export function metricGroupLabel(g: MetricGroup): string {
  return GROUP_LABEL[g];
}

type Partial = Omit<MetricDefinition, 'version' | 'privacyClass' | 'freshness'> & { version?: number; privacyClass?: MetricDefinition['privacyClass']; freshness?: Freshness };
const m = (d: Partial): MetricDefinition => ({ version: 1, privacyClass: 'T1', freshness: 'daily', ...d });

export const METRICS: MetricDefinition[] = [
  /* ---------- 4.1 Access ---------- */
  m({ id: 'ACC.TTA', name: 'Time to appointment', group: 'access', description: 'Median calendar days from order placed to the first booked appointment start, routine priority; urgent shown separately.', formula: 'median(appointment.startsAt − order.createdAt) for first booking per order', grain: 'Appointment', owner: 'BKG lead, PRM', target: 2, targetLabel: '≤ 2 days routine', direction: 'lower', unit: 'days', sources: ['appointments', 'orders'], keywords: ['time to appointment', 'wait for booking', 'lead time', 'third next available', 'access'] }),
  m({ id: 'ACC.OFFER', name: 'Slot offered within request window', group: 'access', description: 'Share of bookings whose first offered slot fell inside the patient’s requested window.', formula: 'appointments with firstOfferInWindow ÷ bookings', grain: 'Appointment', owner: 'BKG lead', target: 85, targetLabel: '≥ 85 %', direction: 'higher', unit: 'pct', sources: ['appointments'], keywords: ['offer', 'request window', 'slot offered'] }),
  m({ id: 'ACC.FILL', name: 'Fill rate', group: 'access', description: 'Booked slot minutes as a share of available slot minutes, excluding blocked slots.', formula: 'booked slot minutes ÷ available slot minutes', grain: 'Slot', owner: 'PRM', target: 85, targetBand: [80, 90], targetLabel: '80–90 %', direction: 'band', unit: 'pct', freshness: 'near_live', sources: ['appointments', 'rooms'], keywords: ['fill rate', 'booked slots', 'capacity filled'] }),
  m({ id: 'ACC.NOSHOW', name: 'No-show rate', group: 'access', description: 'Appointments marked no-show as a share of arrived plus no-show.', formula: 'no_show ÷ (arrived + no_show)', grain: 'Appointment', owner: 'PRM', target: 5, targetLabel: '≤ 5 %', direction: 'lower', unit: 'pct', sources: ['appointments'], keywords: ['no-show', 'no show', 'did not attend', 'dna'] }),
  m({ id: 'ACC.CANCEL', name: 'Cancellation rate', group: 'access', description: 'Cancelled appointments as a share of booked; late cancellations (< 24 h) reported as a subset.', formula: 'cancelled ÷ booked', grain: 'Appointment', owner: 'PRM', target: 8, targetLabel: '≤ 8 %', direction: 'lower', unit: 'pct', sources: ['appointments'], keywords: ['cancellation', 'cancelled', 'late cancel'] }),
  m({ id: 'ACC.WAITCONV', name: 'Waitlist conversion', group: 'access', description: 'Waitlist offers accepted as a share of offers made.', formula: 'waitlist offers accepted ÷ offers made', grain: 'Waitlist entry', owner: 'BKG lead', target: 60, targetLabel: '≥ 60 %', direction: 'higher', unit: 'pct', sources: ['waitlist'], keywords: ['waitlist', 'wait list conversion'] }),
  m({ id: 'ACC.CONV', name: 'Referral conversion', group: 'access', description: 'Orders that reached arrived as a share of referrals received, excluding duplicates.', formula: 'orders arrived ÷ referrals received', grain: 'Referral', owner: 'BKG lead', target: 85, targetLabel: '≥ 85 %', direction: 'higher', unit: 'pct', sources: ['orders', 'appointments'], keywords: ['referral conversion', 'converted', 'attendance from referral'] }),
  m({ id: 'ACC.SELF', name: 'Self-service booking share', group: 'access', description: 'Bookings made through Patient Space or WhatsApp as a share of all bookings.', formula: 'self-service bookings ÷ bookings', grain: 'Appointment', owner: 'BKG lead', target: 50, targetLabel: '≥ 50 %', direction: 'higher', unit: 'pct', sources: ['appointments'], keywords: ['self-service', 'whatsapp booking', 'patient space booking', 'online booking'] }),
  m({ id: 'ACC.AHT', name: 'Contact-centre handling time', group: 'access', description: 'Median duration of BKG interactions per booking outcome.', formula: 'median(interaction duration)', grain: 'Interaction', owner: 'BKG lead', target: 4, targetLabel: '≤ 4 min', direction: 'lower', unit: 'minutes', sources: ['booking_interactions'], keywords: ['handling time', 'call duration', 'contact centre'] }),
  m({ id: 'ACC.HAND', name: 'Booking Hand completion', group: 'access', description: 'Bookings completed end-to-end by the Booking Hand as a share of bookings it started.', formula: 'hand-completed bookings ÷ hand-started bookings', grain: 'Agent task', owner: 'BKG lead', target: 70, targetLabel: '≥ 70 %', direction: 'higher', unit: 'pct', sources: ['agent_tasks'], keywords: ['booking hand', 'hand completion'] }),

  /* ---------- 4.2 Operations ---------- */
  m({ id: 'OPS.UTIL', name: 'Utilisation', group: 'operations', description: 'Scanned minutes (in-room to out-room) as a share of staffed operating minutes, by modality, room and hour of day.', formula: 'scanned minutes ÷ staffed operating minutes', grain: 'Encounter', owner: 'PRM, RAD lead', target: 78, targetBand: [70, 85], targetLabel: 'CT/MR 70–85 %', direction: 'band', unit: 'pct', freshness: 'near_live', sources: ['worklist', 'appointments'], keywords: ['utilisation', 'utilization', 'room usage', 'heatmap', 'busy'] }),
  m({ id: 'OPS.TIR', name: 'Time in room', group: 'operations', description: 'Median out-room minus in-room, case-mix adjusted by the procedure’s expected duration.', formula: 'median(outRoom − inRoom) ÷ expected', grain: 'Encounter', owner: 'RAD lead', target: 1.1, targetLabel: '≤ 1.1 × expected', direction: 'lower', unit: 'ratio', sources: ['worklist'], keywords: ['time in room', 'room time', 'scan duration'] }),
  m({ id: 'OPS.WAIT', name: 'Waiting-room time', group: 'operations', description: 'Median minutes from arrival to in-room for on-time arrivals.', formula: 'median(inRoom − arrived)', grain: 'Encounter', owner: 'PRM', target: 15, targetLabel: '≤ 15 min', direction: 'lower', unit: 'minutes', freshness: 'live', sources: ['registrations', 'worklist'], keywords: ['waiting', 'wait time', 'waiting room', 'queue'] }),
  m({ id: 'OPS.TAT.SEG', name: 'Turnaround: available to signed', group: 'operations', description: 'Median minutes from study available to report signed, by priority.', formula: 'median(report.signedAt − study.availableAt)', grain: 'Study', owner: 'RGT lead', target: 1440, targetLabel: 'routine ≤ 24 h', direction: 'lower', unit: 'minutes', freshness: 'near_live', sources: ['reports', 'studies'], keywords: ['turnaround', 'tat', 'report time', 'signed'] }),
  m({ id: 'OPS.TAT.SLA', name: 'TAT within SLA', group: 'operations', description: 'Studies signed within the priority SLA as a share of studies signed.', formula: 'signed within SLA ÷ signed', grain: 'Study', owner: 'RGT lead', target: 95, targetLabel: '≥ 95 %', direction: 'higher', unit: 'pct', freshness: 'near_live', sources: ['reports'], keywords: ['sla', 'turnaround within', 'tat sla', 'on time reports'] }),
  m({ id: 'OPS.REPEAT', name: 'Repeat/reject rate', group: 'operations', description: 'Repeat exposures as a share of total exposures, by reason; individual figures shown to the radiographer only.', formula: 'repeat exposures ÷ exposures', grain: 'Exposure', owner: 'RAD lead', target: 5, targetLabel: '≤ 5 % projection', direction: 'lower', unit: 'pct', sources: ['exposures', 'worklist'], keywords: ['repeat', 'reject', 'retake'] }),
  m({ id: 'OPS.COMPLETE', name: 'Exam completeness', group: 'operations', description: 'Studies available without an incomplete or QC-hold history.', formula: 'complete studies ÷ studies', grain: 'Study', owner: 'RAD lead', target: 98, targetLabel: '≥ 98 %', direction: 'higher', unit: 'pct', sources: ['studies'], keywords: ['completeness', 'incomplete', 'qc hold'] }),
  m({ id: 'OPS.PROTOCOL', name: 'Protocol adherence', group: 'operations', description: 'Studies acquired on the assigned protocol version.', formula: 'on-protocol studies ÷ studies', grain: 'Study', owner: 'RGT lead', target: 97, targetLabel: '≥ 97 %', direction: 'higher', unit: 'pct', sources: ['worklist'], keywords: ['protocol', 'adherence'] }),
  m({ id: 'OPS.THRU', name: 'Studies per staffed hour', group: 'operations', description: 'RVU-weighted studies completed per staffed radiographer hour; shown raw and case-mix adjusted.', formula: 'weighted studies ÷ staffed RAD hours', grain: 'Shift', owner: 'PRM', target: null, targetLabel: 'per modality baseline', direction: 'higher', unit: 'ratio', sources: ['studies', 'shifts'], keywords: ['throughput', 'studies per hour', 'productivity'] }),
  m({ id: 'OPS.UNSOL', name: 'Unsolicited studies', group: 'operations', description: 'Studies flagged unsolicited (no matching order) as a share of studies.', formula: 'unsolicited ÷ studies', grain: 'Study', owner: 'PRM', target: 0.5, targetLabel: '≤ 0.5 %', direction: 'lower', unit: 'pct', sources: ['studies'], keywords: ['unsolicited', 'unmatched study'] }),
  m({ id: 'OPS.EDGE', name: 'Edge continuity', group: 'operations', description: 'Minutes imaging continued during link or grid outage as a share of outage minutes.', formula: 'continued minutes ÷ outage minutes', grain: 'Site day', owner: 'BIO', target: 100, targetLabel: '100 %', direction: 'higher', unit: 'pct', sources: ['edge_gateways', 'load_shedding_windows'], keywords: ['edge', 'outage', 'continuity', 'load-shedding', 'load shedding'] }),

  /* ---------- 4.3 Clinical quality ---------- */
  m({ id: 'CLQ.PEER', name: 'Peer review discrepancy rate', group: 'clinical_quality', description: 'Peer reviews scored major or critical as a share of reviews.', formula: 'major+critical reviews ÷ reviews', grain: 'Peer review', owner: 'RGT lead, CMP', target: 2, targetLabel: '≤ 2 % major', direction: 'lower', unit: 'pct', sources: ['peer_reviews'], keywords: ['peer review', 'discrepancy'] }),
  m({ id: 'CLQ.PEERCOV', name: 'Peer review coverage', group: 'clinical_quality', description: 'Reports peer-reviewed as a share of reports signed.', formula: 'reviewed ÷ signed', grain: 'Report', owner: 'RGT lead', target: 3, targetLabel: '≥ 3 % plus AI-discordant', direction: 'higher', unit: 'pct', sources: ['peer_reviews', 'reports'], keywords: ['peer review coverage', 'reviewed reports'] }),
  m({ id: 'CLQ.CRIT.ACK', name: 'Critical result acknowledgement time', group: 'clinical_quality', description: 'Median minutes from a critical result raised to referrer acknowledgement; P90 target 60 min.', formula: 'median(acknowledged − raised)', grain: 'Critical result', owner: 'RGT lead', target: 60, targetLabel: 'P90 ≤ 60 min', direction: 'lower', unit: 'minutes', freshness: 'live', sources: ['critical_results'], keywords: ['critical result', 'acknowledgement', 'critical finding', 'ack'] }),
  m({ id: 'CLQ.CRIT.ESC', name: 'Critical results escalated', group: 'clinical_quality', description: 'Escalations as a share of critical results.', formula: 'escalated ÷ critical results', grain: 'Critical result', owner: 'RGT lead', target: 10, targetLabel: '≤ 10 %', direction: 'lower', unit: 'pct', sources: ['critical_results'], keywords: ['escalated critical', 'escalation rate'] }),
  m({ id: 'CLQ.FU', name: 'Follow-up completion', group: 'clinical_quality', description: 'Recommended follow-up imaging booked and completed within interval + 30 days.', formula: 'completed follow-ups ÷ recommendations', grain: 'Structured finding', owner: 'CMP', target: 80, targetLabel: '≥ 80 %', direction: 'higher', unit: 'pct', sources: ['follow_ups'], keywords: ['follow-up', 'follow up', 'lost to follow'] }),
  m({ id: 'CLQ.ADD', name: 'Addendum rate', group: 'clinical_quality', description: 'Addenda as a share of signed reports, by reason.', formula: 'addenda ÷ signed reports', grain: 'Report', owner: 'RGT lead', target: 1.5, targetLabel: '≤ 1.5 %', direction: 'lower', unit: 'pct', sources: ['reports'], keywords: ['addendum', 'addenda', 'amended report'] }),
  m({ id: 'CLQ.DRL', name: 'Dose vs DRL', group: 'clinical_quality', description: 'Median dose metric divided by the diagnostic reference level per protocol and age band; share above DRL.', formula: 'median(dose ÷ DRL)', grain: 'Dose record', owner: 'CMP (RPO)', target: 1, targetLabel: 'median ≤ 1.0', direction: 'lower', unit: 'ratio', sources: ['dose_records'], keywords: ['dose', 'drl', 'reference level', 'radiation dose'] }),
  m({ id: 'CLQ.DOSE.CAP', name: 'Dose capture rate', group: 'clinical_quality', description: 'Ionising studies with an RDSR-sourced dose record.', formula: 'studies with dose record ÷ ionising studies', grain: 'Study', owner: 'CMP (RPO)', target: 99, targetLabel: '≥ 99 %', direction: 'higher', unit: 'pct', sources: ['dose_records', 'studies'], keywords: ['dose capture', 'rdsr'] }),
  m({ id: 'CLQ.CONTRAST', name: 'Contrast reactions', group: 'clinical_quality', description: 'Contrast reactions by severity as a share of contrast administrations.', formula: 'reactions ÷ administrations', grain: 'Encounter', owner: 'NUR lead, CMP', target: 0.3, targetLabel: '≤ 0.3 % mild', direction: 'lower', unit: 'pct', sources: ['contrast_administrations', 'incidents'], keywords: ['contrast reaction', 'extravasation', 'anaphylaxis'] }),
  m({ id: 'CLQ.EGFR', name: 'eGFR check compliance', group: 'clinical_quality', description: 'Contrast CT with eGFR recorded within the policy window.', formula: 'contrast CT with eGFR ÷ contrast CT', grain: 'Encounter', owner: 'NUR lead', target: 100, targetLabel: '100 %', direction: 'higher', unit: 'pct', sources: ['safety_questionnaires'], keywords: ['egfr', 'kidney', 'renal check'] }),
  m({ id: 'CLQ.AI.AGREE', name: 'AI agreement rate', group: 'clinical_quality', description: 'Findings candidates accepted or edited as a share of candidates presented, by model version.', formula: 'accepted+edited ÷ presented', grain: 'Finding candidate', owner: 'AIO', target: null, targetLabel: 'model baseline ± band', direction: 'band', unit: 'pct', sources: ['bci_results'], keywords: ['ai agreement', 'accepted candidates', 'agreement rate'] }),
  m({ id: 'CLQ.AI.OVR', name: 'AI override rate', group: 'clinical_quality', description: 'Candidates rejected as a share of presented, by model version.', formula: 'rejected ÷ presented', grain: 'Finding candidate', owner: 'AIO', target: null, targetLabel: 'per validation report', direction: 'band', unit: 'pct', sources: ['bci_results'], keywords: ['override', 'rejected candidates', 'ai override'] }),
  m({ id: 'CLQ.AI.TRIAGE', name: 'Triage precision', group: 'clinical_quality', description: 'AI-prioritised studies the signed report confirms as critical or urgent.', formula: 'confirmed ÷ prioritised', grain: 'Study', owner: 'AIO', target: null, targetLabel: '≥ validation report', direction: 'higher', unit: 'pct', sources: ['bci_results', 'reports'], keywords: ['triage', 'precision', 'prioritised'] }),
  m({ id: 'CLQ.ICD', name: 'ICD-10 specificity', group: 'clinical_quality', description: 'Claim lines coded at full ICD-10 specificity.', formula: 'specific lines ÷ lines', grain: 'Claim line', owner: 'BIL lead', target: 90, targetLabel: '≥ 90 %', direction: 'higher', unit: 'pct', sources: ['claim_lines'], keywords: ['icd', 'icd-10', 'specificity', 'coding quality'] }),

  /* ---------- 4.4 Patient experience ---------- */
  m({ id: 'PXP.NPS', name: 'NPS', group: 'patient_experience', description: 'Promoters minus detractors as a share of survey responses, per touchpoint.', formula: '(promoters − detractors) ÷ responses', grain: 'Survey response', owner: 'PRM', target: 60, targetLabel: '≥ 60', direction: 'higher', unit: 'score', sources: ['surveys'], keywords: ['nps', 'net promoter', 'satisfaction'] }),
  m({ id: 'PXP.CSAT', name: 'CSAT per touchpoint', group: 'patient_experience', description: 'Responses scoring 4 or 5 out of 5 as a share of responses.', formula: 'responses ≥ 4 ÷ responses', grain: 'Survey response', owner: 'PRM', target: 90, targetLabel: '≥ 90 %', direction: 'higher', unit: 'pct', sources: ['surveys'], keywords: ['csat', 'satisfaction score'] }),
  m({ id: 'PXP.RESP', name: 'Survey response rate', group: 'patient_experience', description: 'Responses as a share of invitations.', formula: 'responses ÷ invitations', grain: 'Invitation', owner: 'PRM', target: 25, targetLabel: '≥ 25 %', direction: 'higher', unit: 'pct', sources: ['surveys'], keywords: ['response rate', 'survey'] }),
  m({ id: 'PXP.QUOTE', name: 'Quote accuracy', group: 'patient_experience', description: 'Quotes where final patient liability equalled the quoted portion within R50.', formula: 'accurate quotes ÷ quotes accepted', grain: 'Quote', owner: 'BIL lead', target: 95, targetLabel: '≥ 95 %', direction: 'higher', unit: 'pct', sources: ['quotes', 'patient_accounts'], keywords: ['quote accuracy', 'quoted', 'surprise'] }),
  m({ id: 'PXP.SURPRISE', name: 'Surprise balance rate', group: 'patient_experience', description: 'Patient statements with liability not disclosed before the visit.', formula: 'undisclosed statements ÷ statements', grain: 'Statement', owner: 'DEB lead', target: 2, targetLabel: '≤ 2 %', direction: 'lower', unit: 'pct', sources: ['statements'], keywords: ['surprise balance', 'undisclosed'] }),
  m({ id: 'PXP.RIH', name: 'Results-in-hand time', group: 'patient_experience', description: 'Median minutes from report signed to results released to the patient.', formula: 'median(released − signed)', grain: 'Report', owner: 'PRM', target: 10, targetLabel: '≤ 10 min where immediate', direction: 'lower', unit: 'minutes', sources: ['results_releases', 'reports'], keywords: ['results in hand', 'results released', 'patient results'] }),
  m({ id: 'PXP.COMPLAINT', name: 'Complaint rate', group: 'patient_experience', description: 'Complaints as a share of encounters, by category.', formula: 'complaints ÷ encounters', grain: 'Complaint', owner: 'CMP', target: 0.2, targetLabel: '≤ 0.2 %', direction: 'lower', unit: 'pct', sources: ['complaints', 'registrations'], keywords: ['complaint rate', 'complaints'] }),
  m({ id: 'PXP.PREP', name: 'Pre-check-in completion', group: 'patient_experience', description: 'Encounters with questionnaire and consent completed before arrival.', formula: 'pre-completed ÷ encounters', grain: 'Encounter', owner: 'FDK lead', target: 70, targetLabel: '≥ 70 %', direction: 'higher', unit: 'pct', sources: ['registrations'], keywords: ['pre-check-in', 'prepare', 'questionnaire before arrival'] }),
  m({ id: 'PXP.LANG', name: 'Language match', group: 'patient_experience', description: 'Communications sent in the patient’s preferred language.', formula: 'matched ÷ communications', grain: 'Communication', owner: 'PRM', target: 95, targetLabel: '≥ 95 %', direction: 'higher', unit: 'pct', sources: ['communications', 'patients'], keywords: ['language', 'preferred language'] }),

  /* ---------- 4.5 Referrer ---------- */
  m({ id: 'REF.VOL', name: 'Referral volume', group: 'referrer', description: 'Referrals received by referrer, organisation, discipline and region; trailing 4 weeks vs prior.', formula: 'count(referrals received)', grain: 'Referral', owner: 'Referrer relations', target: null, targetLabel: 'plan', direction: 'higher', unit: 'count', sources: ['orders'], keywords: ['referral volume', 'referrals', 'referrer volume', 'top referrers'] }),
  m({ id: 'REF.SOW', name: 'Share of wallet', group: 'referrer', description: 'A referrer’s studies at Bonakala as a share of their modelled total imaging referrals (labelled as a model).', formula: 'studies here ÷ modelled total', grain: 'Referrer month', owner: 'Referrer relations', target: null, targetLabel: 'growth', direction: 'higher', unit: 'pct', sources: ['orders', 'referrers'], keywords: ['share of wallet', 'wallet'] }),
  m({ id: 'REF.TAT', name: 'TAT per referrer', group: 'referrer', description: 'Available-to-signed and signed-to-delivered turnaround by referrer.', formula: 'median TAT by referrer', grain: 'Study', owner: 'RGT lead', target: null, targetLabel: 'per SLA', direction: 'lower', unit: 'minutes', sources: ['reports'], keywords: ['referrer turnaround', 'tat by referrer'] }),
  m({ id: 'REF.CHURN', name: 'Churn risk', group: 'referrer', description: 'Active referrers whose volume fell > 40 % vs their 12-week baseline or with no referral in 60 days.', formula: 'at-risk referrers ÷ active referrers', grain: 'Referrer', owner: 'Referrer relations', target: 5, targetLabel: '≤ 5 % of active', direction: 'lower', unit: 'pct', sources: ['orders', 'referrers'], keywords: ['churn', 'dropped', 'lost referrers', 'referrers dropped'] }),
  m({ id: 'REF.NEW', name: 'New referrers', group: 'referrer', description: 'Referrers with a first referral in the period.', formula: 'count(first referral in period)', grain: 'Referrer', owner: 'Referrer relations', target: null, targetLabel: 'plan', direction: 'higher', unit: 'count', sources: ['orders', 'referrers'], keywords: ['new referrers', 'first referral'] }),
  m({ id: 'REF.ACTIVE', name: 'Active referrers', group: 'referrer', description: 'Referrers with at least one referral in the trailing 90 days.', formula: 'count(referrers with ≥ 1 referral in 90 d)', grain: 'Referrer', owner: 'Referrer relations', target: null, targetLabel: 'growth', direction: 'higher', unit: 'count', sources: ['orders', 'referrers'], keywords: ['active referrers', 'referrer count'] }),
  m({ id: 'REF.EREF', name: 'Electronic referral share', group: 'referrer', description: 'Referrals via portal, FHIR or HL7 as a share of referrals.', formula: 'electronic ÷ referrals', grain: 'Referral', owner: 'Referrer relations', target: 60, targetLabel: '≥ 60 %', direction: 'higher', unit: 'pct', sources: ['orders'], keywords: ['e-referral', 'electronic referral', 'portal referral'] }),
  m({ id: 'REF.APPROP', name: 'Appropriateness change rate', group: 'referrer', description: 'Orders changed after an appropriateness suggestion was shown.', formula: 'changed ÷ suggestions shown', grain: 'Order procedure', owner: 'RGT lead', target: null, targetLabel: 'tracked', direction: 'band', unit: 'pct', sources: ['orders'], keywords: ['appropriateness', 'changed order'] }),
  m({ id: 'REF.ATTEND', name: 'Referred patient attendance', group: 'referrer', description: 'Referral conversion by referrer, shown in Referrer Space.', formula: 'arrived ÷ referred, by referrer', grain: 'Referral', owner: 'Referrer relations', target: 85, targetLabel: '≥ 85 %', direction: 'higher', unit: 'pct', sources: ['orders', 'appointments'], keywords: ['referred attendance', 'attendance by referrer'] }),

  /* ---------- 4.6 Revenue cycle ---------- */
  m({ id: 'RCM.FPA', name: 'First-pass acceptance', group: 'revenue_cycle', description: 'Claim lines accepted on first submission as a share of lines submitted.', formula: 'accepted first pass ÷ submitted', grain: 'Claim line', owner: 'BIL lead', target: 95, targetLabel: '≥ 95 %', direction: 'higher', unit: 'pct', freshness: 'near_live', sources: ['claims'], keywords: ['first-pass', 'first pass', 'acceptance', 'clean claim'] }),
  m({ id: 'RCM.REJ', name: 'Rejection rate', group: 'revenue_cycle', description: 'Lines rejected as a share of lines submitted, by reason, funder, site and coder.', formula: 'rejected ÷ submitted', grain: 'Claim line', owner: 'BIL lead', target: 4, targetLabel: '≤ 4 %', direction: 'lower', unit: 'pct', freshness: 'near_live', sources: ['claims'], keywords: ['rejection', 'rejected claims', 'rejections by reason'] }),
  m({ id: 'RCM.REJ.FIX', name: 'Rejection recovery', group: 'revenue_cycle', description: 'Rejected lines eventually paid as a share of rejected lines.', formula: 'recovered ÷ rejected', grain: 'Claim line', owner: 'BIL lead', target: 80, targetLabel: '≥ 80 %', direction: 'higher', unit: 'pct', sources: ['claims'], keywords: ['recovery', 'resubmitted paid', 'fixed rejections'] }),
  m({ id: 'RCM.DTB', name: 'Days to bill', group: 'revenue_cycle', description: 'Median days from service date to claim submitted.', formula: 'median(submitted − service date)', grain: 'Claim', owner: 'BIL lead', target: 1, targetLabel: '≤ 1 day clean claims', direction: 'lower', unit: 'days', sources: ['claims'], keywords: ['days to bill', 'billing lag'] }),
  m({ id: 'RCM.UNBILLED', name: 'Unbilled', group: 'revenue_cycle', description: 'Value of charges in draft, coded, ready or held older than 2 days.', formula: 'sum(unbilled charges > 2 d)', grain: 'Charge', owner: 'BIL lead', target: 2, targetLabel: '≤ 2 % of monthly revenue', direction: 'lower', unit: 'cents', freshness: 'near_live', sources: ['charges'], keywords: ['unbilled', 'awaiting coding', 'held charges'] }),
  m({ id: 'RCM.DSO', name: 'Days sales outstanding', group: 'revenue_cycle', description: 'Debtors balance divided by trailing 90-day net revenue per day, split scheme and patient.', formula: 'debtors ÷ (90-day revenue ÷ 90)', grain: 'Account', owner: 'DEB lead, CFO', target: 35, targetLabel: '≤ 35 days scheme', direction: 'lower', unit: 'days', sources: ['patient_accounts', 'claims'], keywords: ['dso', 'days sales outstanding', 'debtor days'] }),
  m({ id: 'RCM.NCR', name: 'Net collection rate', group: 'revenue_cycle', description: 'Collections as a share of charges less contractual adjustments for a service-month cohort at 180 days.', formula: 'collections ÷ (charges − contractual)', grain: 'Service month', owner: 'CFO', target: 97, targetLabel: '≥ 97 % at 180 d', direction: 'higher', unit: 'pct', sources: ['payments', 'charges'], keywords: ['net collection', 'collection rate'] }),
  m({ id: 'RCM.POS', name: 'Point-of-service collection', group: 'revenue_cycle', description: 'Patient portion collected on the day of service as a share of patient portion quoted.', formula: 'collected at POS ÷ quoted patient portion', grain: 'Encounter', owner: 'FDK lead', target: 90, targetLabel: '≥ 90 %', direction: 'higher', unit: 'pct', freshness: 'live', sources: ['payments', 'quotes'], keywords: ['point of service', 'cash at desk', 'pos collection', 'collected at desk'] }),
  m({ id: 'RCM.AGE', name: 'Debtors over 90 days', group: 'revenue_cycle', description: 'Share of debtors balance older than 90 days.', formula: 'balance > 90 d ÷ balance', grain: 'Account', owner: 'DEB lead', target: 10, targetLabel: '≤ 10 % over 90', direction: 'lower', unit: 'pct', sources: ['patient_accounts'], keywords: ['ageing', 'aging', 'over 90', 'debtors age'] }),
  m({ id: 'RCM.WO', name: 'Write-offs', group: 'revenue_cycle', description: 'Write-offs as a share of gross charges, by reason.', formula: 'write-offs ÷ gross charges', grain: 'Charge', owner: 'DEB lead', target: 1.5, targetLabel: '≤ 1.5 %', direction: 'lower', unit: 'pct', sources: ['charges', 'patient_accounts'], keywords: ['write-off', 'write off', 'bad debt'] }),
  m({ id: 'RCM.C2C', name: 'Cost to collect', group: 'revenue_cycle', description: 'RCM staff, switch, PSP, communication and Hand cost as a share of collections.', formula: 'RCM costs ÷ collections', grain: 'Period', owner: 'CFO', target: 3, targetLabel: '≤ 3 %', direction: 'lower', unit: 'pct', sources: ['journal_lines', 'payments'], keywords: ['cost to collect'] }),
  m({ id: 'RCM.RPS', name: 'Revenue per study', group: 'revenue_cycle', description: 'Net revenue per study by modality, payer class and site.', formula: 'net revenue ÷ studies', grain: 'Study', owner: 'CFO', target: null, targetLabel: 'plan', direction: 'higher', unit: 'cents', sources: ['claims', 'studies'], keywords: ['revenue per study', 'average revenue'] }),
  m({ id: 'RCM.MIX', name: 'Payer mix: scheme share', group: 'revenue_cycle', description: 'Net revenue share billed to medical schemes; cash, RAF, COIDA and corporate shown alongside.', formula: 'scheme revenue ÷ net revenue', grain: 'Period', owner: 'CFO', target: null, targetLabel: 'plan', direction: 'band', unit: 'pct', sources: ['claims'], keywords: ['payer mix', 'funder mix', 'revenue by funder', 'scheme share'] }),
  m({ id: 'RCM.CONTRACT', name: 'Contract performance', group: 'revenue_cycle', description: 'Actual paid per tariff code as a share of the contracted rate.', formula: 'paid ÷ contracted', grain: 'Claim line', owner: 'BIL lead', target: 99, targetLabel: '≥ 99 %', direction: 'higher', unit: 'pct', sources: ['remittances'], keywords: ['contract performance', 'paid below contract', 'short payment'] }),
  m({ id: 'RCM.DEADLINE', name: 'Resubmission deadline risk', group: 'revenue_cycle', description: 'Value of rejected lines within 30 days of the funder’s resubmission deadline.', formula: 'sum(rejected value near deadline)', grain: 'Claim line', owner: 'BIL lead', target: 0, targetLabel: 'R 0', direction: 'lower', unit: 'cents', sources: ['claims'], keywords: ['deadline', 'resubmission', 'stale rejections'] }),
  m({ id: 'RCM.PLAN', name: 'Payment plan performance', group: 'revenue_cycle', description: 'Instalments paid on time as a share of instalments due.', formula: 'paid on time ÷ due', grain: 'Payment plan', owner: 'DEB lead', target: 85, targetLabel: '≥ 85 %', direction: 'higher', unit: 'pct', sources: ['payment_plans'], keywords: ['payment plan', 'instalment'] }),
  m({ id: 'RCM.DISPUTE', name: 'Disputes open age', group: 'revenue_cycle', description: 'Median age of open disputes in days.', formula: 'median(now − opened) for open disputes', grain: 'Dispute', owner: 'DEB lead', target: 14, targetLabel: '≤ 14 days', direction: 'lower', unit: 'days', sources: ['disputes'], keywords: ['dispute', 'disputes open'] }),
  m({ id: 'RCM.AUTO', name: 'Straight-through claims', group: 'revenue_cycle', description: 'Claims that reached submitted with no human touch.', formula: 'untouched submitted ÷ claims', grain: 'Claim', owner: 'BIL lead', target: 85, targetLabel: '≥ 85 %', direction: 'higher', unit: 'pct', sources: ['claims'], keywords: ['straight-through', 'automated claims', 'no touch'] }),

  /* ---------- 4.7 Finance ---------- */
  m({ id: 'FIN.REV', name: 'Net revenue', group: 'finance', description: 'Gross charges less contractual adjustments and write-offs, accrual basis.', formula: 'gross − contractual − write-offs', grain: 'Period', owner: 'CFO', target: null, targetLabel: 'budget', direction: 'higher', unit: 'cents', freshness: 'monthly', sources: ['journal_lines', 'claims'], keywords: ['revenue', 'net revenue', 'turnover', 'sales'] }),
  m({ id: 'FIN.EBITDA', name: 'EBITDA margin', group: 'finance', description: 'EBITDA as a share of net revenue, operating costs allocated by intercompany drivers.', formula: '(revenue − operating costs) ÷ revenue', grain: 'Period', owner: 'CFO', target: 25, targetLabel: 'plan 25 %', direction: 'higher', unit: 'pct', freshness: 'monthly', sources: ['journal_lines'], keywords: ['ebitda', 'margin', 'profit'] }),
  m({ id: 'FIN.MARGIN.SITE', name: 'Contribution margin per site', group: 'finance', description: 'Revenue less direct costs (staff, consumables, reading fees, equipment) per site and modality.', formula: 'revenue − direct costs', grain: 'Period', owner: 'CFO', target: null, targetLabel: 'budget', direction: 'higher', unit: 'cents', freshness: 'monthly', sources: ['journal_lines'], keywords: ['contribution margin', 'site margin'] }),
  m({ id: 'FIN.CPS', name: 'Cost per study', group: 'finance', description: 'Total allocated cost per study, by modality.', formula: 'allocated cost ÷ studies', grain: 'Study', owner: 'CFO', target: null, targetLabel: 'benchmark', direction: 'lower', unit: 'cents', freshness: 'monthly', sources: ['journal_lines', 'studies'], keywords: ['cost per study', 'unit cost'] }),
  m({ id: 'FIN.IC', name: 'Intercompany days to settle', group: 'finance', description: 'Median days from intercompany invoice to settlement.', formula: 'median(settled − issued)', grain: 'Invoice', owner: 'CFO', target: 30, targetLabel: 'settled ≤ 30 days', direction: 'lower', unit: 'days', freshness: 'monthly', sources: ['intercompany_invoices'], keywords: ['intercompany', 'management fee', 'settle'] }),
  m({ id: 'FIN.DIST', name: 'Distributions days to pay', group: 'finance', description: 'Days from period close to distribution payment.', formula: 'paid date − period close', grain: 'Period', owner: 'CFO', target: 45, targetLabel: '≤ 45 days', direction: 'lower', unit: 'days', freshness: 'monthly', sources: ['distributions'], keywords: ['distribution', 'dividend', 'payout'] }),
  m({ id: 'FIN.VAR', name: 'Budget variance', group: 'finance', description: 'Actual minus budget per line and KPI with driver decomposition.', formula: '(actual − budget) ÷ budget', grain: 'Period', owner: 'CFO', target: 0, targetBand: [-5, 5], targetLabel: 'within ± 5 %', direction: 'band', unit: 'pct', freshness: 'monthly', sources: ['budgets', 'journal_lines'], keywords: ['variance', 'budget', 'vs plan'] }),
  m({ id: 'FIN.CASH', name: 'Cash and runway', group: 'finance', description: 'Closing cash with a 13-week forecast; collections vs forecast.', formula: 'closing cash', grain: 'Week', owner: 'CFO', target: null, targetLabel: 'plan', direction: 'higher', unit: 'cents', sources: ['bank_balances'], keywords: ['cash', 'runway', 'cash forecast'] }),
  m({ id: 'FIN.CAPEX', name: 'Capex return', group: 'finance', description: 'Incremental EBITDA of an asset divided by its cost, tracked against the business case.', formula: 'incremental EBITDA ÷ cost', grain: 'Asset', owner: 'CFO', target: null, targetLabel: 'business case', direction: 'higher', unit: 'pct', freshness: 'monthly', sources: ['assets', 'journal_lines'], keywords: ['capex', 'return on asset', 'payback'] }),

  /* ---------- 4.8 Workforce ---------- */
  m({ id: 'WFM.SPF', name: 'Studies per FTE (case-mix adjusted)', group: 'workforce', description: 'RVU-weighted studies per FTE worked, by role and modality; raw and adjusted side by side.', formula: 'weighted studies ÷ FTE worked', grain: 'Period', owner: 'PRM, Group HR', target: null, targetLabel: 'benchmark', direction: 'higher', unit: 'ratio', sources: ['studies', 'staff'], keywords: ['studies per fte', 'per fte', 'staff productivity'] }),
  m({ id: 'WFM.OT', name: 'Overtime share', group: 'workforce', description: 'Overtime hours as a share of worked hours.', formula: 'overtime hours ÷ worked hours', grain: 'Shift', owner: 'PRM', target: 5, targetLabel: '≤ 5 %', direction: 'lower', unit: 'pct', sources: ['time_attendance', 'shifts'], keywords: ['overtime'] }),
  m({ id: 'WFM.VAC', name: 'Gap hours', group: 'workforce', description: 'Unfilled roster hours as a share of planned hours.', formula: 'open gap hours ÷ planned hours', grain: 'Roster', owner: 'PRM', target: 3, targetLabel: '≤ 3 %', direction: 'lower', unit: 'pct', freshness: 'near_live', sources: ['shifts'], keywords: ['gaps', 'open shifts', 'vacancies', 'unfilled', 'roster gap'] }),
  m({ id: 'WFM.ABS', name: 'Absence', group: 'workforce', description: 'Absent shifts as a share of published shifts.', formula: 'absent ÷ published', grain: 'Shift', owner: 'PRM', target: 3, targetLabel: '≤ 3 %', direction: 'lower', unit: 'pct', sources: ['shifts', 'leave'], keywords: ['absence', 'sick', 'absent'] }),
  m({ id: 'WFM.CRED', name: 'Credentials expiring in 30 days', group: 'workforce', description: 'Staff with a mandatory credential expiring within 30 days; expired must be 0 rostered.', formula: 'count(credentials expiring ≤ 30 d)', grain: 'Staff', owner: 'PRM, CMP', target: 0, targetLabel: '0 expired', direction: 'lower', unit: 'count', sources: ['credentials'], keywords: ['credential', 'hpcsa expiry', 'registration expiring', 'expiring'] }),
  m({ id: 'WFM.CPD', name: 'CPD compliance', group: 'workforce', description: 'Staff on track for cycle points as a share of staff in scope.', formula: 'on-pace staff ÷ staff', grain: 'Staff', owner: 'CMP', target: 100, targetLabel: '100 %', direction: 'higher', unit: 'pct', sources: ['cpd_points', 'staff'], keywords: ['cpd', 'ceu', 'continuing education'] }),
  m({ id: 'WFM.RGT', name: 'Radiologist throughput', group: 'workforce', description: 'RVU-weighted reports signed per reading hour (private to RGT and RGT lead).', formula: 'weighted reports ÷ reading hours', grain: 'Shift', owner: 'RGT lead', target: null, targetLabel: 'benchmark', direction: 'higher', unit: 'ratio', privacyClass: 'T0', sources: ['reports', 'shifts'], keywords: ['radiologist throughput', 'reports per hour'] }),
  m({ id: 'WFM.HAND', name: 'Roster Hand fill', group: 'workforce', description: 'Gaps filled by the Roster Hand as a share of gaps detected.', formula: 'hand-filled gaps ÷ gaps', grain: 'Gap', owner: 'PRM', target: 60, targetLabel: '≥ 60 %', direction: 'higher', unit: 'pct', sources: ['shifts'], keywords: ['roster hand', 'gaps filled'] }),

  /* ---------- 4.9 Assets ---------- */
  m({ id: 'AST.UP', name: 'Uptime', group: 'assets', description: 'Operating minutes less unplanned downtime as a share of operating minutes, per modality.', formula: '(operating − unplanned down) ÷ operating', grain: 'Asset day', owner: 'BIO', target: 98, targetLabel: '≥ 98 %', direction: 'higher', unit: 'pct', freshness: 'near_live', sources: ['assets', 'work_orders'], keywords: ['uptime', 'downtime', 'availability'] }),
  m({ id: 'AST.MTBF', name: 'MTBF', group: 'assets', description: 'Operating hours per unplanned failure, trailing 12 months.', formula: 'operating hours ÷ unplanned failures', grain: 'Asset', owner: 'BIO', target: null, targetLabel: 'vendor baseline', direction: 'higher', unit: 'hours', sources: ['work_orders'], keywords: ['mtbf', 'failures', 'time between failures'] }),
  m({ id: 'AST.MTTR', name: 'MTTR', group: 'assets', description: 'Median hours from downtime start to end for corrective jobs.', formula: 'median(downtimeEnded − downtimeStarted)', grain: 'Job', owner: 'BIO', target: 8, targetLabel: '≤ 8 h', direction: 'lower', unit: 'hours', sources: ['work_orders'], keywords: ['mttr', 'repair time', 'time to repair'] }),
  m({ id: 'AST.PM', name: 'Preventive maintenance on time', group: 'assets', description: 'PM jobs completed by their due date.', formula: 'PM done by due ÷ PM due', grain: 'Job', owner: 'BIO', target: 95, targetLabel: '≥ 95 %', direction: 'higher', unit: 'pct', sources: ['work_orders', 'assets'], keywords: ['preventive maintenance', 'pm on time', 'maintenance due'] }),
  m({ id: 'AST.QA', name: 'QA compliance', group: 'assets', description: 'QA tests completed by due as a share of due.', formula: 'QA done by due ÷ QA due', grain: 'Test', owner: 'BIO, RPO', target: 100, targetLabel: '100 %', direction: 'higher', unit: 'pct', sources: ['modalities', 'qa_tests'], keywords: ['qa', 'quality assurance', 'qa due', 'constancy'] }),
  m({ id: 'AST.LIC', name: 'Licences expiring in 90 days', group: 'assets', description: 'Room and device licences expiring within 90 days; expired in use must be 0.', formula: 'count(licences expiring ≤ 90 d)', grain: 'Licence', owner: 'CMP, BIO', target: 0, targetLabel: '0 expired', direction: 'lower', unit: 'count', sources: ['rooms'], keywords: ['licence', 'license', 'sahpra licence', 'licence expiry'] }),
  m({ id: 'AST.CONTRAST', name: 'Contrast stock days', group: 'assets', description: 'On-hand contrast volume divided by trailing 28-day daily usage, per site.', formula: 'on hand ÷ daily usage', grain: 'Site day', owner: 'PRM, NUR', target: 20, targetBand: [10, 30], targetLabel: '10–30 days', direction: 'band', unit: 'days', freshness: 'near_live', sources: ['consumables'], keywords: ['contrast', 'stock', 'days cover', 'vials'] }),
  m({ id: 'AST.PRED', name: 'Predictive alarms open', group: 'assets', description: 'Assets with an active predictive signal at warn or critical level.', formula: 'count(assets with signal ≥ warn)', grain: 'Alarm', owner: 'BIO', target: null, targetLabel: 'tracked', direction: 'lower', unit: 'count', sources: ['assets', 'telemetry'], keywords: ['predictive', 'tube arc', 'helium', 'failure risk', 'telemetry'] }),
  m({ id: 'AST.LINK', name: 'Edge backlog minutes', group: 'assets', description: 'Transfer backlog across site gateways; UPS events counted separately.', formula: 'max(backlog studies × 2 min)', grain: 'Site day', owner: 'BIO', target: 15, targetLabel: 'backlog ≤ 15 min', direction: 'lower', unit: 'minutes', freshness: 'live', sources: ['edge_gateways'], keywords: ['gateway', 'backlog', 'tunnel', 'connectivity', 'ups'] }),

  /* ---------- 4.10 Compliance ---------- */
  m({ id: 'CMP.INC', name: 'Open incidents', group: 'compliance', description: 'Open incidents by severity and age; incidents per 1 000 studies alongside.', formula: 'count(incidents not closed)', grain: 'Incident', owner: 'CMP', target: null, targetLabel: 'tracked', direction: 'lower', unit: 'count', freshness: 'live', sources: ['incidents'], keywords: ['incident', 'incidents open', 'adverse event'] }),
  m({ id: 'CMP.CLOSE', name: 'Incident closure time', group: 'compliance', description: 'Median days from reported to closed, by severity.', formula: 'median(closed − reported)', grain: 'Incident', owner: 'CMP', target: 30, targetLabel: 'sev 1–2 ≤ 30 days', direction: 'lower', unit: 'days', sources: ['incidents'], keywords: ['closure time', 'incident closed', 'time to close'] }),
  m({ id: 'CMP.POPIA', name: 'POPIA requests in time', group: 'compliance', description: 'Data-subject requests fulfilled within the statutory period as a share of fulfilled.', formula: 'in time ÷ fulfilled', grain: 'Request', owner: 'CMP (Information Officer)', target: 100, targetLabel: '100 % in time', direction: 'higher', unit: 'pct', sources: ['data_subject_requests'], keywords: ['popia', 'paia', 'data subject', 'access request', 'information officer'] }),
  m({ id: 'CMP.BREACH', name: 'Break-glass reviewed', group: 'compliance', description: 'Break-glass opens reviewed within 5 days as a share of opens; data breach incidents counted separately.', formula: 'reviewed in 5 d ÷ opens', grain: 'Event', owner: 'CMP', target: 100, targetLabel: 'reviewed 100 %', direction: 'higher', unit: 'pct', sources: ['audit_log'], keywords: ['break-glass', 'break glass', 'breach'] }),
  m({ id: 'CMP.AUDIT', name: 'Audit findings open', group: 'compliance', description: 'Open findings by severity with overdue count.', formula: 'count(findings open)', grain: 'Finding', owner: 'CMP', target: 0, targetLabel: '0 overdue major', direction: 'lower', unit: 'count', sources: ['audit_findings'], keywords: ['audit', 'findings', 'non-conformance'] }),
  m({ id: 'CMP.POLICY', name: 'Policy acknowledgement', group: 'compliance', description: 'Staff who acknowledged the current version of mandatory policies as a share of staff in scope.', formula: 'acknowledged ÷ in scope', grain: 'Policy', owner: 'CMP', target: 100, targetLabel: '100 % within 14 days', direction: 'higher', unit: 'pct', sources: ['policy_acknowledgements', 'staff'], keywords: ['policy', 'acknowledgement', 'acknowledged'] }),
  m({ id: 'CMP.LIC', name: 'Licence and registration currency', group: 'compliance', description: 'Rooms with a valid licence and clinical staff with verified HPCSA as a share of the total.', formula: 'current ÷ total', grain: 'Day', owner: 'CMP', target: 100, targetLabel: '100 %', direction: 'higher', unit: 'pct', sources: ['rooms', 'credentials'], keywords: ['currency', 'registration current', 'hpcsa verified'] }),
  m({ id: 'CMP.CHAIN', name: 'Audit chain integrity', group: 'compliance', description: 'Days with a verified hash chain as a share of days.', formula: 'verified days ÷ days', grain: 'Day', owner: 'CMP, SUP', target: 100, targetLabel: '100 %', direction: 'higher', unit: 'pct', sources: ['audit_log'], keywords: ['audit chain', 'hash chain', 'integrity'] }),
  m({ id: 'CMP.CAL', name: 'Obligations overdue', group: 'compliance', description: 'Obligations past due without a recorded submission; due in 30 days shown alongside.', formula: 'count(obligations overdue)', grain: 'Obligation', owner: 'CMP', target: 0, targetLabel: '0 overdue', direction: 'lower', unit: 'count', freshness: 'live', sources: ['obligations'], keywords: ['obligation', 'overdue', 'calendar', 'regulatory', 'statutory', 'due'] }),
  m({ id: 'CMP.RR', name: 'Reportable results open', group: 'compliance', description: 'Reportable-result flags raised and not yet closed, by category; unacknowledged flags escalate weekly.', formula: 'count(reportable results open or acknowledged)', grain: 'Reportable result', owner: 'CMP, PRM', target: null, targetLabel: 'tracked', direction: 'lower', unit: 'count', freshness: 'live', sources: ['reportable_results'], keywords: ['reportable', 'notifiable', 'tb', 'safeguarding', 'flags'] }),

  /* ---------- 4.11 AI operations ---------- */
  m({ id: 'AIO.LAT', name: 'Inference latency', group: 'ai_ops', description: 'Median minutes from study available to inference finished, by model version and site.', formula: 'median(finished − available)', grain: 'Job', owner: 'AIO', target: 5, targetLabel: 'P95 ≤ 5 min triage', direction: 'lower', unit: 'minutes', freshness: 'near_live', sources: ['inference_jobs'], keywords: ['latency', 'inference time', 'ai speed'] }),
  m({ id: 'AIO.COV', name: 'Coverage', group: 'ai_ops', description: 'Eligible studies that received a model result.', formula: 'with result ÷ eligible', grain: 'Study', owner: 'AIO', target: 98, targetLabel: '≥ 98 %', direction: 'higher', unit: 'pct', sources: ['inference_jobs', 'studies'], keywords: ['coverage', 'ai coverage'] }),
  m({ id: 'AIO.FAIL', name: 'Inference failure rate', group: 'ai_ops', description: 'Failed inference jobs as a share of jobs.', formula: 'failed ÷ jobs', grain: 'Job', owner: 'AIO', target: 1, targetLabel: '≤ 1 %', direction: 'lower', unit: 'pct', sources: ['inference_jobs'], keywords: ['inference failure', 'failed jobs'] }),
  m({ id: 'AIO.DRIFT', name: 'Drift alarms open', group: 'ai_ops', description: 'Model versions whose weekly input or output statistics sit outside the validation band.', formula: 'count(drift alarms open)', grain: 'Model week', owner: 'AIO', target: 0, targetLabel: 'within band', direction: 'band', unit: 'count', sources: ['model_monitoring'], keywords: ['drift', 'distribution shift'] }),
  m({ id: 'AIO.EXPIRED', name: 'Undecided candidates', group: 'ai_ops', description: 'Candidates that expired at sign-off without a decision.', formula: 'expired ÷ presented', grain: 'Candidate', owner: 'AIO', target: 2, targetLabel: '≤ 2 %', direction: 'lower', unit: 'pct', sources: ['bci_results'], keywords: ['undecided', 'expired candidates'] }),
  m({ id: 'AIO.SLIP', name: 'AI slip incidents', group: 'ai_ops', description: 'Incidents of type ai_slip in the period; always shown, target zero, non-zero links to the incident.', formula: 'count(incidents where category = ai_slip)', grain: 'Incident', owner: 'AIO, CMP', target: 0, targetLabel: '0', direction: 'lower', unit: 'count', freshness: 'live', sources: ['incidents', 'bci_monitoring'], keywords: ['ai slip', 'slip', 'unverified ai'] }),
  m({ id: 'AIO.HAND', name: 'Hand completion rate', group: 'ai_ops', description: 'Hand tasks completed as a share of started; escalations and approval rate alongside.', formula: 'done ÷ started', grain: 'Task', owner: 'AIO', target: null, targetLabel: 'per mandate', direction: 'band', unit: 'pct', freshness: 'near_live', sources: ['agent_tasks'], keywords: ['hand outcomes', 'hand tasks', 'agent tasks', 'approvals'] }),
  m({ id: 'AIO.HAND.REV', name: 'Hand reversal rate', group: 'ai_ops', description: 'Hand actions rolled back or corrected by a human within 7 days.', formula: 'reversed ÷ executed', grain: 'Action', owner: 'AIO', target: 0.5, targetLabel: '≤ 0.5 %', direction: 'lower', unit: 'pct', sources: ['agent_tasks'], keywords: ['reversal', 'rolled back'] }),
  m({ id: 'AIO.VAL', name: 'Validation currency', group: 'ai_ops', description: 'Deployed models with a validation report younger than 12 months.', formula: 'current validations ÷ deployed models', grain: 'Model', owner: 'AIO', target: 100, targetLabel: '100 %', direction: 'higher', unit: 'pct', sources: ['models'], keywords: ['validation', 'model validation'] }),

  /* ---------- 4.12 Shareholder ---------- */
  m({ id: 'SHR.DP', name: 'Distributable profit', group: 'shareholder', description: 'EBITDA less capex, working-capital and tax reserves and debt service, per entity and period.', formula: 'EBITDA − reserves − tax − debt service', grain: 'Period', owner: 'CFO, SHR', target: null, targetLabel: 'plan', direction: 'higher', unit: 'cents', freshness: 'monthly', sources: ['journal_lines', 'distributions'], keywords: ['distributable', 'profit for distribution'] }),
  m({ id: 'SHR.PAID', name: 'Distribution timeliness', group: 'shareholder', description: 'Days from period close to payment; paid as a share of declared.', formula: 'paid date − close', grain: 'Distribution', owner: 'CFO', target: 45, targetLabel: '≤ 45 days; 100 %', direction: 'lower', unit: 'days', freshness: 'monthly', sources: ['distributions'], keywords: ['distribution paid', 'payout timing'] }),
  m({ id: 'SHR.PLAN', name: 'KPI vs plan', group: 'shareholder', description: 'Actual as a share of budget for revenue, studies, EBITDA, DSO, TAT and NPS.', formula: 'actual ÷ budget', grain: 'Period', owner: 'CFO', target: 100, targetLabel: '≥ 100 %', direction: 'higher', unit: 'pct', freshness: 'monthly', sources: ['budgets', 'journal_lines'], keywords: ['vs plan', 'against budget', 'kpi vs plan'] }),
  m({ id: 'SHR.RM', name: 'Reserved matters open', group: 'shareholder', description: 'Open reserved-matter approvals and their age.', formula: 'count(open reserved matters)', grain: 'Approval', owner: 'EXE', target: 10, targetLabel: '≤ 10 days', direction: 'lower', unit: 'count', sources: ['reserved_matters'], keywords: ['reserved matters', 'shareholder approval'] }),
  m({ id: 'SHR.VAL', name: 'Trailing 12-month studies', group: 'shareholder', description: 'Context indicators for valuation: trailing 12-month studies (EBITDA, net debt and active referrers alongside); not a valuation.', formula: 'sum(studies, trailing 12 months)', grain: 'Period', owner: 'CFO', target: null, targetLabel: 'tracked', direction: 'higher', unit: 'count', freshness: 'monthly', sources: ['studies'], keywords: ['valuation', 'trailing twelve months', 'ttm', 'value indicators'] }),
];

const byId = new Map(METRICS.map((d) => [d.id, d]));
export function getMetric(id: string): MetricDefinition | undefined {
  return byId.get(id);
}
export function metricsByGroup(): Array<{ group: MetricGroup; label: string; metrics: MetricDefinition[] }> {
  const groups = [...new Set(METRICS.map((d) => d.group))];
  return groups.map((g) => ({ group: g, label: GROUP_LABEL[g], metrics: METRICS.filter((d) => d.group === g) }));
}

/** Is the value on target? Returns 'ok' | 'att' | 'crit' | 'none' for tile toning. */
export function assessAgainstTarget(def: MetricDefinition, value: number | null): 'ok' | 'att' | 'crit' | 'none' {
  if (value === null || value === undefined || Number.isNaN(value)) return 'none';
  if (def.direction === 'band') {
    if (!def.targetBand) return 'none';
    const [lo, hi] = def.targetBand;
    if (value >= lo && value <= hi) return 'ok';
    const span = hi - lo || 1;
    return value < lo - span * 0.5 || value > hi + span * 0.5 ? 'crit' : 'att';
  }
  if (def.target === null) return 'none';
  const t = def.target;
  if (def.direction === 'higher') {
    if (value >= t) return 'ok';
    return value >= t * 0.9 ? 'att' : 'crit';
  }
  if (value <= t) return 'ok';
  return value <= t * 1.25 || value - t <= 1 ? 'att' : 'crit';
}
